// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbsedqjxdwcgcxpmnjek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdic2VkcWp4ZHdjZ2N4cG1uamVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjEwOTksImV4cCI6MjA2NTczNzA5OX0.uvHn7S7IYLfhaQ3ACLOIATXYwHUhuMg1imlicDksvjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);